// examples/nextjs/app/CheckoutButton.tsx
'use client'

import type { KlappayOneError, PaymentResult } from '@klappay/one'
import dynamic from 'next/dynamic'
import { useState } from 'react'

const KlappayButton = dynamic(() => import('@klappay/one/react').then((mod) => mod.KlappayButton), {
  ssr: false,
})

const defaultOrigin = process.env.NEXT_PUBLIC_KLAP_ONE_ORIGIN ?? ''

export function CheckoutButton() {
  const [origin, setOrigin] = useState(defaultOrigin)
  const [chargeId, setChargeId] = useState('')
  const [applied, setApplied] = useState({ origin: '', chargeId: '' })
  const [status, setStatus] = useState('')

  const ready = Boolean(origin && chargeId)

  return (
    <div>
      <label>
        Klap One origin
        <input
          value={origin}
          onChange={(e) => setOrigin(e.target.value)}
          placeholder="https://klap.one"
        />
      </label>
      <label>
        Charge ID
        <input
          value={chargeId}
          onChange={(e) => setChargeId(e.target.value)}
          placeholder="ch_123"
        />
      </label>
      <button type="button" onClick={() => setApplied({ origin, chargeId })} disabled={!ready}>
        {ready ? 'Generate button' : 'Fill in origin and charge ID first'}
      </button>

      {/* Renders disabled on its own until both charge-id/origin are set —
          the lib handles that reactively, no need to conditionally mount it. */}
      <KlappayButton
        chargeId={applied.chargeId}
        origin={applied.origin}
        variant="black"
        size="lg"
        onSuccess={(result: PaymentResult) => setStatus(`Paid! tx: ${result.txHash}`)}
        onError={(error: KlappayOneError) => setStatus(`Error: ${error.message}`)}
        onCancel={() => setStatus('Checkout closed.')}
      />
      <p>{status}</p>
    </div>
  )
}

// examples/nuxt/app/components/CheckoutButton.vue
<script setup lang="ts">
// A type-only import is erased at build time — this side-effecting import
// is what actually registers <klappay-button> as a Custom Element.
import '@klappay/one'
import type { KlappayOneError, PaymentResult } from '@klappay/one'
import { computed, reactive, ref } from 'vue'

const runtimeConfig = useRuntimeConfig()

const origin = ref(runtimeConfig.public.klapOneOrigin)
const chargeId = ref('')
const applied = reactive({ origin: '', chargeId: '' })
const status = ref('')

const ready = computed(() => Boolean(origin.value && chargeId.value))

function generate(): void {
  applied.origin = origin.value
  applied.chargeId = chargeId.value
}

function onSuccess(event: Event): void {
  const result = (event as CustomEvent<PaymentResult>).detail
  status.value = `Paid! tx: ${result.txHash}`
}

function onError(event: Event): void {
  const error = (event as CustomEvent<KlappayOneError>).detail
  status.value = `Error: ${error.message}`
}

function onCancel(): void {
  status.value = 'Checkout closed.'
}
</script>

<template>
  <div>
    <label>
      Klappay One origin
      <input v-model="origin" placeholder="https://klap.one" />
    </label>
    <label>
      Charge ID
      <input v-model="chargeId" placeholder="ch_123" />
    </label>
    <button type="button" :disabled="!ready" @click="generate">
      {{ ready ? 'Generate button' : 'Fill in origin and charge ID first' }}
    </button>

    <!-- Renders disabled on its own until both charge-id/origin are set —
         the lib handles that reactively, no need for a v-if here. -->
    <klappay-button
      :charge-id="applied.chargeId"
      :origin="applied.origin"
      @success="onSuccess"
      @error="onError"
      @cancel="onCancel"
    />
    <p v-if="status">{{ status }}</p>
  </div>
</template>
